namespace Gu.Wpf.PropertyGrid
{
    using System;
    using System.Windows;

    // Don't think I'll be using this as it confuses with R# static analysis
    internal static partial class Grid
    {
        public static readonly DependencyProperty AutoGeneratePropertyGridColumnsProperty = DependencyProperty.RegisterAttached(
            "AutoGeneratePropertyGridColumns",
            typeof(bool),
            typeof(Grid),
            new FrameworkPropertyMetadata(
                default(bool),
                FrameworkPropertyMetadataOptions.NotDataBindable,
                AutoGeneratePropertyGridColumnsChanged));

        public static void SetAutoGeneratePropertyGridColumns(this System.Windows.Controls.Grid element, bool value)
        {
            element.SetValue(AutoGeneratePropertyGridColumnsProperty, value);
        }

        [AttachedPropertyBrowsableForChildren(IncludeDescendants = false)]
        [AttachedPropertyBrowsableForType(typeof(Grid))]
        public static bool GetAutoGeneratePropertyGridColumns(this System.Windows.Controls.Grid element)
        {
            return (bool)element.GetValue(AutoGeneratePropertyGridColumnsProperty);
        }

        private static void AutoGeneratePropertyGridColumnsChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            if ((bool)e.NewValue)
            {
                var grid = (System.Windows.Controls.Grid)d;
                grid.ColumnDefinitions.Clear();
                grid.ColumnDefinitions.Add(CreateColumnDefinition("Header"));
                grid.ColumnDefinitions.Add(CreateColumnDefinition("Value"));
                grid.ColumnDefinitions.Add(CreateColumnDefinition("Suffix"));
            }
            else
            {
                throw new NotSupportedException("Does nolt support removing autogenerated columns, don't think it will ever be useful.");
            }
        }

        private static System.Windows.Controls.ColumnDefinition CreateColumnDefinition(string source)
        {
            var columnDefinition = new System.Windows.Controls.ColumnDefinition();
            ColumnDefinition.SetSource(columnDefinition, source);
            return columnDefinition;
        }
    }
}